services:
  server-web:
    image: nginx:stable-alpine
    container_name: server-web
    profiles:
      - application
    ports:
      - "8080:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./src:/var/www/html

  php-fpm:
    build:
      dockerfile: php.dockerfile
      context: ./dockerfiles
    container_name: php-fpm
    profiles:
      - application
    volumes:
      - ./src:/var/www/html

  mysql:
    image: mysql:8
    container_name: mysql
    profiles:
      - application
    env_file:
      - ./env/mysql.env

# Utilitarios

  composer:
    build:
      dockerfile: composer.dockerfile
      context: ./dockerfiles
    profiles:
      - util
    volumes:
      - ./src:/var/www/html

  artisan:
    build:
      dockerfile: php.dockerfile
      context: ./dockerfiles
    profiles:
      - util
    volumes:
      - ./src:/var/www/html
    entrypoint: ["php", "/var/www/html/artisan"]

  npm:
    image: node:18.19.1-alpine
    container_name: npm
    working_dir: /var/www/html
    profiles:
      - util
    volumes:
      - ./src:/var/www/html
    entrypoint: ["npm"]