apiVersion: v1
kind: Namespace
metadata:
  name: ns-dev
  labels:
    env: dev
    app: frontend
---    
apiVersion: v1
kind: Namespace
metadata:
  name: ns-prd
  labels:
    env: prd
    app: frontend
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rs-nginx
  labels:
    env: dev
    app: frontend
  namespace: ns-dev
spec:
  replicas: 3
  selector:
    matchLabels:
      env: dev
      app: frontend
  template:
    metadata:
      labels:
        env: dev
        app: frontend
    spec:
      containers:
        - name: container01
          image: nginx:alpine
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rs-nginx
  labels:
    env: prd
    app: frontend
  namespace: ns-prd
spec:
  replicas: 5
  selector:
    matchLabels:
      env: prd
      app: frontend
  template:
    metadata:
      labels:
        env: prd
        app: frontend
    spec:
      containers:
        - name: container01
          image: nginx:alpine          