apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: read-pods
subjects:
  - kind: User
    name: course_16
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: Pod
metadata:
  name: server-web
spec:
  containers:
    - name: web
      image: nginx:alpine
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cm-dev
data:
  api_url: https://dev-api.mycompany.com
  kafka_url: http://svc-kafka:9000