apiVersion: v1
kind: ServiceAccount
metadata:
  name: sa-dev
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-backend
  labels:
    env: dev
    app: backend
spec:
  replicas: 5
  selector:
    matchLabels:
      env: dev
      app: backend
  template:
    metadata:
      labels:
        env: dev
        app: backend
    spec:
      serviceAccountName: sa-dev
      containers:
        - name: server-web
          image: nginx:alpine
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: dev-reader
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "watch", "list", "delete"]
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["get", "watch", "list", "patch", "delete"]         
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: read-pods
subjects:
  - kind: ServiceAccount
    name: sa-dev
    apiGroup: ""
roleRef:
  kind: Role
  name: dev-reader
  apiGroup: rbac.authorization.k8s.io     