FROM node:20-alpine AS build

ARG DIR

WORKDIR /build

COPY ${DIR}/package.json .

RUN npm install

COPY ${DIR}/ .

RUN npm run build

FROM nginx:alpine AS prod

COPY --from=build /build/dist /usr/share/nginx/html

CMD ["nginx", "-g", "daemon off;"]