services:
  server-nginx:
    image: nginx:latest
    container_name: server-nginx
    ports:
      - "8080:80"
    working_dir: /app
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./www:/app:ro