apiVersion: v1
kind: Pod
metadata:
  name: pod-nginx-sonarqube
  labels:
    env: dev
    app: frontend
spec:
  containers:
    - name: web
      image: nginx:alpine
    - name: sonarqube
      image: sonarqube:alpine