apiVersion: v1
kind: Pod
metadata:
  name: pod-nginx
  labels:
    env: dev
    app: frontend
spec:
  containers:
    - name: web
      image: nginx:alpine
---
apiVersion: v1
kind: Pod
metadata:
  name: pod-sonar
  labels:
    env: dev
    app: frontend
spec:
  containers:
    - name: sonar
      image: sonarqube:alpine