apiVersion: apps/v1
kind: Deployment
metadata:
  name: rs-nginx
  labels:
    env: dev
    app: backend
spec:
  replicas: 5
  selector:
    matchLabels:
      env: dev
      app: backend
  template:
    metadata:
      labels:
        env: dev
        app: backend
    spec:
      containers:
        - name: container01
          image: python:3.6-alpine
          command: [
            "sh",
            "-c",
            "echo 'pagina cerrada' > index.html && python -m http.server 8082"
          ]